"""Thesis memory: ground truth for research, with no model in the loop.

Every executed thesis-backed trade is graded against a benchmark from daily
closes at horizon-relative checkpoints (spec §5).  Grades aggregate into a
calibration bucket (spec §6) that the research packet reports and the risk
engine may act on.  Everything here is arithmetic on ``Decimal``; the only
network call is the daily-bars fetch, and it is research-grade data that never
becomes a reference price.
"""

from __future__ import annotations

import datetime as dt
import uuid
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass
from decimal import ROUND_HALF_EVEN, Decimal

from stockbrain.enums import OutcomeCheckpoint, ThesisAction, TimeHorizon
from stockbrain.market_data.base import Bar
from stockbrain.risk.exits import EXIT_PRECEDENCE
from stockbrain.risk.models import CalibrationBucket

__all__ = [
    "BARS_DAYS",
    "CHECKPOINTS",
    "EXIT_RULE_IDS",
    "EffectiveGrade",
    "bar_on_or_before",
    "calibrate",
    "checkpoints_for",
    "entry_bar",
    "is_correct",
    "returns",
    "trading_days_after",
]

#: Enough daily bars to cover the longest checkpoint (D60) with a margin for
#: holidays, fetched once per symbol per tick.
BARS_DAYS = 120

#: Horizon-relative checkpoints (spec §5.2).  Not a setting: a checkpoint
#: schedule that changed under stored grades would make them incomparable.
CHECKPOINTS: Mapping[TimeHorizon, tuple[OutcomeCheckpoint, ...]] = {
    TimeHorizon.INTRADAY: (OutcomeCheckpoint.D1, OutcomeCheckpoint.D5),
    TimeHorizon.DAYS: (OutcomeCheckpoint.D1, OutcomeCheckpoint.D5),
    TimeHorizon.WEEKS: (OutcomeCheckpoint.D5, OutcomeCheckpoint.D20),
    TimeHorizon.MONTHS: (OutcomeCheckpoint.D20, OutcomeCheckpoint.D60),
}

#: A proposal whose recorded rules include one of these was generated by the
#: exit sweep, not by research.
EXIT_RULE_IDS: frozenset[str] = frozenset(EXIT_PRECEDENCE)

_SIX_PLACES = Decimal("0.000001")
_RISK_REDUCING = frozenset({ThesisAction.REDUCE, ThesisAction.SELL})


def checkpoints_for(horizon: TimeHorizon) -> tuple[OutcomeCheckpoint, ...]:
    return CHECKPOINTS[horizon]


def entry_bar(bars: Sequence[Bar], entry_date: dt.date) -> Bar | None:
    """The close on the entry date, or the first session after it.

    A fill on a weekend or holiday (a deferred proposal executed at the next
    open) has no bar of its own; the next session's close is the honest entry.
    """
    for candidate in bars:
        if candidate.timestamp.date() >= entry_date:
            return candidate
    return None


def bar_on_or_before(bars: Sequence[Bar], day: dt.date) -> Bar | None:
    """The last close on or before ``day``; bars are oldest first."""
    found: Bar | None = None
    for candidate in bars:
        if candidate.timestamp.date() > day:
            break
        found = candidate
    return found


def trading_days_after(bars: Sequence[Bar], entry_date: dt.date) -> int:
    """Sessions strictly after the entry date -- the checkpoint clock."""
    return sum(1 for candidate in bars if candidate.timestamp.date() > entry_date)


def returns(
    entry_close: Decimal,
    current_close: Decimal,
    benchmark_entry: Decimal,
    benchmark_current: Decimal,
) -> tuple[Decimal, Decimal, Decimal]:
    """``(instrument_return, benchmark_return, alpha)`` as exact ratios."""
    if entry_close <= 0 or benchmark_entry <= 0:
        raise ValueError("entry close must be positive")
    instrument = current_close / entry_close - Decimal(1)
    benchmark = benchmark_current / benchmark_entry - Decimal(1)
    return instrument, benchmark, instrument - benchmark


def is_correct(action: ThesisAction, alpha: Decimal) -> bool:
    """Signed by the action: a BUY wants alpha above zero, a trim wants it below."""
    if action is ThesisAction.BUY:
        return alpha > 0
    if action in _RISK_REDUCING:
        return alpha < 0
    raise ValueError(f"{action.value} cannot be graded: it never produces a trade")


@dataclass(frozen=True, slots=True)
class EffectiveGrade:
    """The one grade that stands for an outcome: CLOSE if graded, else the latest."""

    outcome_id: uuid.UUID
    correct: bool
    alpha: Decimal
    graded_at: dt.datetime


def calibrate(key: str, grades: Iterable[EffectiveGrade]) -> CalibrationBucket | None:
    rows = list(grades)
    if not rows:
        return None
    samples = len(rows)
    correct = sum(1 for row in rows if row.correct)
    hit_rate = (Decimal(correct) / Decimal(samples)).quantize(_SIX_PLACES, ROUND_HALF_EVEN)
    mean_alpha = (sum((row.alpha for row in rows), Decimal(0)) / Decimal(samples)).quantize(
        _SIX_PLACES, ROUND_HALF_EVEN
    )
    return CalibrationBucket(
        key=key,
        samples=samples,
        correct=correct,
        hit_rate=hit_rate.normalize() if hit_rate == hit_rate.to_integral() else hit_rate,
        mean_alpha=mean_alpha.normalize() if mean_alpha == mean_alpha.to_integral() else mean_alpha,
        latest_graded_at=max(row.graded_at for row in rows),
    )
