"""Thesis memory: ground truth for research, with no model in the loop.

Every executed thesis-backed trade is graded against a benchmark from daily
closes at horizon-relative checkpoints (spec §5).  Grades aggregate into a
calibration bucket (spec §6) that the research packet reports and the risk
engine may act on.  Everything here is arithmetic on ``Decimal``; the only
network call is the daily-bars fetch, and it is research-grade data that never
becomes a reference price.
"""

from __future__ import annotations

import datetime as dt
import uuid
from collections import Counter
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass
from decimal import ROUND_HALF_EVEN, Decimal

import sqlalchemy as sa
from sqlalchemy.ext.asyncio import AsyncSession

from stockbrain.config import Settings
from stockbrain.db.base import utcnow
from stockbrain.db.models.companies import BrokerInstrument
from stockbrain.db.models.memory import ThesisOutcome, ThesisOutcomeGrade
from stockbrain.db.models.portfolio import Position
from stockbrain.db.models.proposals import TradeProposal
from stockbrain.db.models.research import ResearchRun, Thesis
from stockbrain.db.models.sources import Event
from stockbrain.db.session import Database
from stockbrain.enums import (
    Broker,
    OrderSide,
    OutcomeCheckpoint,
    OutcomeStatus,
    ProposalStatus,
    ResearchStatus,
    ThesisAction,
    TimeHorizon,
)
from stockbrain.errors import ProviderError
from stockbrain.intelligence.research import (
    CalibrationRecord,
    PositionMemory,
    ResearchMemory,
    StandingThesis,
)
from stockbrain.logging import get_logger
from stockbrain.market_data.base import Bar
from stockbrain.market_data.yahoo import DailyBars, yahoo_symbol
from stockbrain.risk.exits import EXIT_PRECEDENCE
from stockbrain.risk.models import CalibrationBucket

__all__ = [
    "BARS_DAYS",
    "CHECKPOINTS",
    "ENTRY_BAR_TOLERANCE_DAYS",
    "EXIT_RULE_IDS",
    "MAX_BARS_DAYS",
    "EffectiveGrade",
    "MemoryService",
    "bar_on_or_before",
    "calibrate",
    "checkpoints_for",
    "entry_bar",
    "is_correct",
    "returns",
    "trading_days_after",
]

#: Enough daily bars to cover the longest checkpoint (D60) with a margin for
#: holidays, fetched once per symbol per tick.
BARS_DAYS = 120

#: The widest window one tick will ask Yahoo for, so an old outcome cannot make
#: the sweep request an unbounded amount of history.
MAX_BARS_DAYS = 400

#: An entry bar further than this many days after ``entry_date`` is not the
#: entry: the series starts after the fill rather than around it.
ENTRY_BAR_TOLERANCE_DAYS = 7

#: Horizon-relative checkpoints (spec §5.2).  Not a setting: a checkpoint
#: schedule that changed under stored grades would make them incomparable.
CHECKPOINTS: Mapping[TimeHorizon, tuple[OutcomeCheckpoint, ...]] = {
    TimeHorizon.INTRADAY: (OutcomeCheckpoint.D1, OutcomeCheckpoint.D5),
    TimeHorizon.DAYS: (OutcomeCheckpoint.D1, OutcomeCheckpoint.D5),
    TimeHorizon.WEEKS: (OutcomeCheckpoint.D5, OutcomeCheckpoint.D20),
    TimeHorizon.MONTHS: (OutcomeCheckpoint.D20, OutcomeCheckpoint.D60),
}

#: A proposal whose recorded rules include one of these was generated by the
#: exit sweep, not by research.
EXIT_RULE_IDS: frozenset[str] = frozenset(EXIT_PRECEDENCE)

_SIX_PLACES = Decimal("0.000001")
_RISK_REDUCING = frozenset({ThesisAction.REDUCE, ThesisAction.SELL})


def checkpoints_for(horizon: TimeHorizon) -> tuple[OutcomeCheckpoint, ...]:
    return CHECKPOINTS[horizon]


def entry_bar(bars: Sequence[Bar], entry_date: dt.date) -> Bar | None:
    """The close on the entry date, or the first session after it.

    A fill on a weekend or holiday (a deferred proposal executed at the next
    open) has no bar of its own; the next session's close is the honest entry.
    """
    for candidate in bars:
        if candidate.timestamp.date() >= entry_date:
            return candidate
    return None


def bar_on_or_before(bars: Sequence[Bar], day: dt.date) -> Bar | None:
    """The last close on or before ``day``; bars are oldest first."""
    found: Bar | None = None
    for candidate in bars:
        if candidate.timestamp.date() > day:
            break
        found = candidate
    return found


def trading_days_after(bars: Sequence[Bar], entry_date: dt.date) -> int:
    """Sessions strictly after the entry date -- the checkpoint clock."""
    return sum(1 for candidate in bars if candidate.timestamp.date() > entry_date)


def returns(
    entry_close: Decimal,
    current_close: Decimal,
    benchmark_entry: Decimal,
    benchmark_current: Decimal,
) -> tuple[Decimal, Decimal, Decimal]:
    """``(instrument_return, benchmark_return, alpha)`` as exact ratios."""
    if entry_close <= 0 or benchmark_entry <= 0:
        raise ValueError("entry close must be positive")
    instrument = current_close / entry_close - Decimal(1)
    benchmark = benchmark_current / benchmark_entry - Decimal(1)
    return instrument, benchmark, instrument - benchmark


def is_correct(action: ThesisAction, alpha: Decimal) -> bool:
    """Signed by the action: a BUY wants alpha above zero, a trim wants it below."""
    if action is ThesisAction.BUY:
        return alpha > 0
    if action in _RISK_REDUCING:
        return alpha < 0
    raise ValueError(f"{action.value} cannot be graded: it never produces a trade")


@dataclass(frozen=True, slots=True)
class EffectiveGrade:
    """The one grade that stands for an outcome: CLOSE if graded, else the latest."""

    outcome_id: uuid.UUID
    correct: bool
    alpha: Decimal
    graded_at: dt.datetime


def calibrate(key: str, grades: Iterable[EffectiveGrade]) -> CalibrationBucket | None:
    rows = list(grades)
    if not rows:
        return None
    samples = len(rows)
    correct = sum(1 for row in rows if row.correct)
    hit_rate = (Decimal(correct) / Decimal(samples)).quantize(_SIX_PLACES, ROUND_HALF_EVEN)
    mean_alpha = (sum((row.alpha for row in rows), Decimal(0)) / Decimal(samples)).quantize(
        _SIX_PLACES, ROUND_HALF_EVEN
    )
    return CalibrationBucket(
        key=key,
        samples=samples,
        correct=correct,
        hit_rate=hit_rate.normalize() if hit_rate == hit_rate.to_integral() else hit_rate,
        mean_alpha=mean_alpha.normalize() if mean_alpha == mean_alpha.to_integral() else mean_alpha,
        latest_graded_at=max(row.graded_at for row in rows),
    )


log = get_logger(__name__)

#: A symbol fetched more recently than this is not fetched again (spec §5.5).
_MIN_REFRESH_INTERVAL = dt.timedelta(hours=20)

_TALLY_KEYS = (
    "considered",
    "graded",
    "closed",
    "abandoned",
    "skipped_fresh",
    "skipped_not_due",
    "failed",
)


@dataclass(frozen=True, slots=True)
class _Pending:
    outcome: ThesisOutcome
    symbol: str | None
    exchange: str | None
    held: bool
    sold_at: dt.datetime | None
    sold_rule: str | None


class MemoryService:
    """Records thesis outcomes and grades them; the scheduler's entry point is ``tick``."""

    def __init__(
        self,
        database: Database,
        settings: Settings,
        *,
        bars: DailyBars,
        broker: Broker = Broker.TRADING212,
    ) -> None:
        self._database = database
        self._settings = settings
        self._bars = bars
        self._broker = broker

    # ------------------------------------------------------------------
    # Record (spec §5.1)
    # ------------------------------------------------------------------
    async def record(self, *, now: dt.datetime | None = None) -> int:
        """One outcome per EXECUTED thesis-backed proposal; idempotent."""
        moment = now or utcnow()
        async with self._database.transaction() as session:
            rows = (
                await session.execute(
                    sa.select(
                        TradeProposal, Thesis, ResearchRun, Event.event_type, BrokerInstrument
                    )
                    .join(Thesis, Thesis.id == TradeProposal.thesis_id)
                    .join(ResearchRun, ResearchRun.id == Thesis.research_run_id)
                    .join(Event, Event.id == ResearchRun.event_id, isouter=True)
                    # The run's resolved listing, always set; the proposal's own
                    # ``broker_instrument_id`` is nullable and the test seeds omit it.
                    .join(
                        BrokerInstrument,
                        BrokerInstrument.id == ResearchRun.broker_instrument_id,
                    )
                    .where(
                        TradeProposal.status == ProposalStatus.EXECUTED,
                        TradeProposal.thesis_id.is_not(None),
                        TradeProposal.executed_at.is_not(None),
                        TradeProposal.broker == self._broker,
                        ~sa.exists(
                            sa.select(ThesisOutcome.id).where(
                                ThesisOutcome.proposal_id == TradeProposal.id
                            )
                        ),
                    )
                    .order_by(TradeProposal.executed_at)
                    .limit(200)
                )
            ).all()
            created = 0
            for proposal, thesis, run, event_type, instrument in rows:
                action = ThesisAction(proposal.research_action or proposal.side.value)
                if action not in {ThesisAction.BUY, ThesisAction.REDUCE, ThesisAction.SELL}:
                    continue
                exit_rule = _exit_rule_of(proposal.risk_rules)
                assert proposal.executed_at is not None
                session.add(
                    ThesisOutcome(
                        proposal_id=proposal.id,
                        thesis_id=thesis.id,
                        research_run_id=run.id,
                        company_id=run.company_id,
                        broker_instrument_id=instrument.id,
                        broker=proposal.broker,
                        broker_ticker=proposal.broker_ticker,
                        event_type=event_type,
                        action=action,
                        horizon=thesis.time_horizon,
                        confidence=Decimal(str(proposal.research_confidence or 0)),
                        is_exit=exit_rule is not None,
                        exit_rule_id=exit_rule,
                        entry_at=proposal.executed_at,
                        entry_date=proposal.executed_at.astimezone(dt.UTC).date(),
                        reference_price=proposal.reference_price,
                        currency=instrument.currency,
                        benchmark_symbol=self._settings.memory_benchmark_symbol,
                        created_at=moment,
                        updated_at=moment,
                    )
                )
                created += 1
        if created:
            log.info("thesis_memory_recorded", outcomes=created)
        return created

    # ------------------------------------------------------------------
    # Grade (spec §5.2-§5.5)
    # ------------------------------------------------------------------
    async def grade(self, *, now: dt.datetime | None = None) -> dict[str, int]:
        moment = now or utcnow()
        counts: Counter[str] = Counter(dict.fromkeys(_TALLY_KEYS, 0))
        pending = await self._load_pending(moment, counts)
        if not pending:
            return dict(counts)

        symbols = {item.symbol for item in pending if item.symbol} | {
            self._settings.memory_benchmark_symbol
        }
        # Size one window to the oldest entry still pending, so a BUY held for
        # months is still graded against the close on its own entry date.  The
        # cap keeps a very old outcome from asking for unbounded history.
        oldest = min(item.outcome.entry_date for item in pending)
        age = (moment.date() - oldest).days
        window = min(MAX_BARS_DAYS, max(BARS_DAYS, age + 10))
        series: dict[str, tuple[Sequence[Bar], str]] = {}
        failed_symbols: set[str] = set()
        for symbol in sorted(symbols):
            try:
                series[symbol] = await self._bars.daily_bars(symbol, days=window)
            except ProviderError as exc:
                failed_symbols.add(symbol)
                log.warning("thesis_memory_bars_failed", symbol=symbol, error=str(exc)[:200])

        benchmark = series.get(self._settings.memory_benchmark_symbol)
        for item in pending:
            outcome = item.outcome
            try:
                if (moment.date() - outcome.entry_date).days > MAX_BARS_DAYS:
                    await self._abandon(outcome.id, "entry_outside_window", moment)
                    counts["abandoned"] += 1
                    continue
                if item.symbol is None:
                    await self._abandon(outcome.id, "no_yahoo_symbol", moment)
                    counts["abandoned"] += 1
                    continue
                if item.symbol in failed_symbols or benchmark is None:
                    await self._stamp_attempt(outcome.id, moment)
                    counts["failed"] += 1
                    continue
                bars, currency = series[item.symbol]
                if outcome.currency and currency != outcome.currency:
                    await self._abandon(outcome.id, f"currency_mismatch:{currency}", moment)
                    counts["abandoned"] += 1
                    continue
                graded, closed, ok = await self._grade_one(
                    outcome, item, bars, benchmark[0], moment
                )
                if not ok:
                    counts["failed"] += 1
                    continue
                counts["graded"] += graded
                counts["closed"] += closed
                if not graded and not closed:
                    counts["skipped_not_due"] += 1
            except Exception as exc:  # one outcome never sinks the tick
                counts["failed"] += 1
                log.exception(
                    "thesis_memory_grade_failed", outcome_id=str(outcome.id), error=str(exc)[:200]
                )
                await self._stamp_attempt(outcome.id, moment)
        log.info("thesis_memory_grade_completed", **counts)
        return dict(counts)

    async def tick(self) -> None:
        await self.record()
        await self.grade()

    # ------------------------------------------------------------------
    async def _load_pending(self, moment: dt.datetime, counts: Counter[str]) -> list[_Pending]:
        async with self._database.session() as session:
            rows = (
                await session.execute(
                    sa.select(
                        ThesisOutcome, BrokerInstrument.exchange, BrokerInstrument.market_symbol
                    )
                    .join(
                        BrokerInstrument, BrokerInstrument.id == ThesisOutcome.broker_instrument_id
                    )
                    .where(
                        ThesisOutcome.status == OutcomeStatus.PENDING,
                        ThesisOutcome.broker == self._broker,
                    )
                    .order_by(ThesisOutcome.entry_at)
                    .limit(500)
                )
            ).all()
            pending: list[_Pending] = []
            for outcome, exchange, market_symbol in rows:
                counts["considered"] += 1
                if (
                    outcome.last_attempt_at is not None
                    and moment - outcome.last_attempt_at < _MIN_REFRESH_INTERVAL
                ):
                    counts["skipped_fresh"] += 1
                    continue
                held = (
                    await session.scalar(
                        sa.select(sa.func.count())
                        .select_from(Position)
                        .where(
                            Position.broker == self._broker,
                            Position.broker_ticker == outcome.broker_ticker,
                            Position.quantity > 0,
                        )
                    )
                    or 0
                ) > 0
                sold = (
                    await session.execute(
                        sa.select(TradeProposal.executed_at, TradeProposal.risk_rules)
                        .where(
                            TradeProposal.broker == self._broker,
                            TradeProposal.broker_ticker == outcome.broker_ticker,
                            TradeProposal.status == ProposalStatus.EXECUTED,
                            TradeProposal.side == OrderSide.SELL,
                            TradeProposal.executed_at > outcome.entry_at,
                        )
                        .order_by(TradeProposal.executed_at.desc())
                        .limit(1)
                    )
                ).first()
                pending.append(
                    _Pending(
                        outcome=outcome,
                        symbol=yahoo_symbol(
                            outcome.broker_ticker, exchange, market_symbol=market_symbol
                        ),
                        exchange=exchange,
                        held=held,
                        sold_at=sold[0] if sold else None,
                        sold_rule=_exit_rule_of(sold[1]) if sold else None,
                    )
                )
            return pending

    async def _grade_one(
        self,
        outcome: ThesisOutcome,
        item: _Pending,
        bars: Sequence[Bar],
        benchmark: Sequence[Bar],
        moment: dt.datetime,
    ) -> tuple[int, int, bool]:
        """Grade every due checkpoint (and CLOSE) for one outcome.

        Returns ``(graded, closed, ok)``; ``ok`` is false when the entry bar
        could not be located, in which case nothing is graded.
        """
        entry = entry_bar(bars, outcome.entry_date)
        bench_entry = entry_bar(benchmark, outcome.entry_date)
        if (
            entry is None
            or bench_entry is None
            or (entry.timestamp.date() - outcome.entry_date).days > ENTRY_BAR_TOLERANCE_DAYS
            or (bench_entry.timestamp.date() - outcome.entry_date).days > ENTRY_BAR_TOLERANCE_DAYS
        ):
            log.warning(
                "thesis_memory_entry_bar_missing",
                outcome_id=str(outcome.id),
                entry_date=outcome.entry_date.isoformat(),
                first_bar=bars[0].timestamp.date().isoformat() if bars else None,
            )
            await self._stamp_attempt(outcome.id, moment)
            return 0, 0, False
        days = trading_days_after(bars, outcome.entry_date)
        async with self._database.transaction() as session:
            row = await session.get(ThesisOutcome, outcome.id, with_for_update=True)
            assert row is not None
            existing = set(
                await session.scalars(
                    sa.select(ThesisOutcomeGrade.checkpoint).where(
                        ThesisOutcomeGrade.outcome_id == row.id
                    )
                )
            )
            graded = 0
            closed = 0
            # Checkpoints are graded against the latest close.
            latest = bars[-1]
            bench_latest = benchmark[-1]
            schedule = checkpoints_for(row.horizon)
            for checkpoint in schedule:
                needed = checkpoint.trading_days
                assert needed is not None
                if checkpoint.value in existing or days < needed:
                    continue
                session.add(
                    _grade_row(
                        row, checkpoint, days, entry, latest, bench_entry, bench_latest, moment
                    )
                )
                existing.add(checkpoint.value)
                graded += 1

            # Close (spec §5.4).
            if row.action is ThesisAction.BUY and not row.is_exit and not item.held:
                closed_at = item.sold_at or moment
                close_day = closed_at.astimezone(dt.UTC).date()
                at_close = bar_on_or_before(bars, close_day)
                bench_close = bar_on_or_before(benchmark, close_day)
                if at_close is not None and bench_close is not None:
                    if OutcomeCheckpoint.CLOSE.value not in existing:
                        session.add(
                            _grade_row(
                                row,
                                OutcomeCheckpoint.CLOSE,
                                trading_days_after(bars, row.entry_date)
                                - trading_days_after(bars, close_day),
                                entry,
                                at_close,
                                bench_entry,
                                bench_close,
                                moment,
                            )
                        )
                        graded += 1
                    row.status = OutcomeStatus.CLOSED
                    row.closed_at = closed_at
                    row.close_reason = item.sold_rule or (
                        "sell_executed" if item.sold_at else "position_gone"
                    )
                    closed = 1
            elif row.action is not ThesisAction.BUY or row.is_exit:
                # Trims, sells and exits never close; they retire after their last checkpoint.
                if all(checkpoint.value in existing for checkpoint in schedule):
                    row.status = OutcomeStatus.CLOSED
                    row.closed_at = moment
                    row.close_reason = "checkpoints_complete"
                    closed = 1
            row.last_attempt_at = moment
            row.updated_at = moment
        return graded, closed, True

    async def _stamp_attempt(self, outcome_id: uuid.UUID, moment: dt.datetime) -> None:
        async with self._database.transaction() as session:
            await session.execute(
                sa.update(ThesisOutcome)
                .where(ThesisOutcome.id == outcome_id)
                .values(last_attempt_at=moment, updated_at=moment)
            )

    async def _abandon(self, outcome_id: uuid.UUID, reason: str, moment: dt.datetime) -> None:
        async with self._database.transaction() as session:
            await session.execute(
                sa.update(ThesisOutcome)
                .where(ThesisOutcome.id == outcome_id)
                .values(
                    status=OutcomeStatus.ABANDONED,
                    closed_at=moment,
                    close_reason=reason,
                    last_attempt_at=moment,
                    updated_at=moment,
                )
            )

    # ------------------------------------------------------------------
    # Read side (spec §6, §7.1)
    # ------------------------------------------------------------------
    async def effective_grades(
        self,
        session: AsyncSession,
        *,
        as_of: dt.datetime,
        event_type: str | None = None,
        company_id: uuid.UUID | None = None,
        action: ThesisAction | None = None,
        exits: bool = False,
    ) -> list[EffectiveGrade]:
        """One grade per outcome: CLOSE if graded by ``as_of``, else the latest."""
        stmt = (
            sa.select(
                ThesisOutcomeGrade.outcome_id,
                ThesisOutcomeGrade.checkpoint,
                ThesisOutcomeGrade.correct,
                ThesisOutcomeGrade.alpha,
                ThesisOutcomeGrade.graded_at,
            )
            .join(ThesisOutcome, ThesisOutcome.id == ThesisOutcomeGrade.outcome_id)
            .where(
                ThesisOutcomeGrade.graded_at <= as_of,
                ThesisOutcome.broker == self._broker,
                ThesisOutcome.is_exit.is_(exits),
            )
        )
        if event_type is not None:
            stmt = stmt.where(ThesisOutcome.event_type == event_type)
        if company_id is not None:
            stmt = stmt.where(ThesisOutcome.company_id == company_id)
        if action is not None:
            stmt = stmt.where(ThesisOutcome.action == action)
        chosen: dict[uuid.UUID, tuple[bool, EffectiveGrade]] = {}
        for outcome_id, checkpoint, correct, alpha, graded_at in await session.execute(stmt):
            grade = EffectiveGrade(
                outcome_id=outcome_id, correct=correct, alpha=alpha, graded_at=graded_at
            )
            is_close = checkpoint == OutcomeCheckpoint.CLOSE.value
            current = chosen.get(outcome_id)
            if (
                current is None
                or (is_close and not current[0])
                or (is_close == current[0] and graded_at > current[1].graded_at)
            ):
                chosen[outcome_id] = (is_close, grade)
        return [grade for _, grade in chosen.values()]

    async def calibration(
        self,
        session: AsyncSession,
        *,
        event_type: str | None,
        action: ThesisAction,
        as_of: dt.datetime,
    ) -> CalibrationBucket | None:
        if event_type is None:
            return None
        grades = await self.effective_grades(
            session, as_of=as_of, event_type=event_type, action=action
        )
        return calibrate(f"{event_type}×{action.value}", grades)  # noqa: RUF001

    async def company_calibration(
        self,
        session: AsyncSession,
        *,
        company_id: uuid.UUID,
        action: ThesisAction,
        as_of: dt.datetime,
    ) -> CalibrationBucket | None:
        grades = await self.effective_grades(
            session, as_of=as_of, company_id=company_id, action=action
        )
        return calibrate(f"company:{company_id}×{action.value}", grades)  # noqa: RUF001

    async def research_memory(
        self,
        session: AsyncSession,
        *,
        company_id: uuid.UUID,
        broker_instrument_id: uuid.UUID,
        broker_ticker: str,
        event_type: str | None,
        as_of: dt.datetime,
    ) -> ResearchMemory:
        standing = await self._standing_thesis(session, company_id, broker_instrument_id, as_of)
        position = await self._position_memory(session, broker_ticker, as_of)
        company = await self.company_calibration(
            session, company_id=company_id, action=ThesisAction.BUY, as_of=as_of
        )
        by_type: list[CalibrationRecord] = []
        for action in (ThesisAction.BUY, ThesisAction.REDUCE, ThesisAction.SELL):
            bucket = await self.calibration(
                session, event_type=event_type, action=action, as_of=as_of
            )
            if bucket is not None:
                by_type.append(_record(bucket))
        return ResearchMemory(
            standing_thesis=standing,
            position=position,
            company_record=_record(company) if company else None,
            event_type_record=tuple(by_type),
        )

    async def _standing_thesis(
        self,
        session: AsyncSession,
        company_id: uuid.UUID,
        broker_instrument_id: uuid.UUID,
        as_of: dt.datetime,
    ) -> StandingThesis | None:
        floor = as_of - dt.timedelta(days=self._settings.memory_standing_thesis_max_age_days)
        row = (
            await session.execute(
                sa.select(Thesis, ResearchRun.completed_at)
                .join(ResearchRun, ResearchRun.id == Thesis.research_run_id)
                .where(
                    ResearchRun.company_id == company_id,
                    ResearchRun.broker_instrument_id == broker_instrument_id,
                    ResearchRun.status == ResearchStatus.SUCCEEDED,
                    ResearchRun.completed_at <= as_of,
                    ResearchRun.completed_at >= floor,
                )
                .order_by(ResearchRun.completed_at.desc(), Thesis.id)
                .limit(1)
            )
        ).first()
        if row is None:
            return None
        thesis, completed_at = row
        assert completed_at is not None
        conditions = thesis.invalidation_conditions.get("items", [])
        return StandingThesis(
            thesis_id=thesis.id,
            published_at=completed_at,
            action=thesis.action,
            confidence=thesis.confidence,
            horizon=thesis.time_horizon,
            thesis=(thesis.summary or "")[:600],
            invalidation_conditions=tuple(str(item) for item in conditions),
            age_hours=(as_of - completed_at).total_seconds() / 3600,
        )

    async def _position_memory(
        self, session: AsyncSession, broker_ticker: str, as_of: dt.datetime
    ) -> PositionMemory | None:
        position = (
            await session.execute(
                sa.select(Position)
                .where(
                    Position.broker == self._broker,
                    Position.broker_ticker == broker_ticker,
                    Position.quantity > 0,
                    Position.last_synced_at <= as_of,
                )
                .order_by(Position.last_synced_at.desc())
                .limit(1)
            )
        ).scalar_one_or_none()
        if position is None:
            return None
        unrealised: Decimal | None = None
        if position.average_price and position.current_price:
            unrealised = (
                (position.current_price - position.average_price) / position.average_price
            ).quantize(_SIX_PLACES, ROUND_HALF_EVEN)
        return PositionMemory(
            quantity=position.quantity,
            average_price=position.average_price,
            current_price=position.current_price,
            unrealised_pct=unrealised,
            opened_at=position.initial_fill_date,
            synced_at=position.last_synced_at,
        )


def _record(bucket: CalibrationBucket) -> CalibrationRecord:
    return CalibrationRecord(
        key=bucket.key,
        samples=bucket.samples,
        correct=bucket.correct,
        hit_rate=bucket.hit_rate,
        mean_alpha=bucket.mean_alpha,
        latest_graded_at=bucket.latest_graded_at,
    )


def _exit_rule_of(rules: object) -> str | None:
    """The exit rule id recorded on a proposal's ``risk_rules``, if any."""
    if not isinstance(rules, list):
        return None
    for rule in rules:
        if isinstance(rule, dict) and rule.get("rule_id") in EXIT_RULE_IDS:
            return str(rule["rule_id"])
    return None


def _grade_row(
    outcome: ThesisOutcome,
    checkpoint: OutcomeCheckpoint,
    trading_days: int,
    entry: Bar,
    current: Bar,
    bench_entry: Bar,
    bench_current: Bar,
    moment: dt.datetime,
) -> ThesisOutcomeGrade:
    instrument, benchmark, alpha = returns(
        entry.close, current.close, bench_entry.close, bench_current.close
    )
    return ThesisOutcomeGrade(
        outcome_id=outcome.id,
        checkpoint=checkpoint.value,
        trading_days=trading_days,
        entry_close=entry.close,
        current_close=current.close,
        benchmark_entry_close=bench_entry.close,
        benchmark_current_close=bench_current.close,
        instrument_return=instrument.quantize(_SIX_PLACES, ROUND_HALF_EVEN),
        benchmark_return=benchmark.quantize(_SIX_PLACES, ROUND_HALF_EVEN),
        alpha=alpha.quantize(_SIX_PLACES, ROUND_HALF_EVEN),
        correct=is_correct(outcome.action, alpha),
        graded_at=moment,
    )
