"""Discovery topic registry.

Topics are stored in PostgreSQL and edited by the user, not hard-coded into
logic. The list below is only the *initial seed*, applied once when the table is
empty; after that the database is authoritative and a redeploy never resurrects
a topic the user disabled or deleted.

Query strings are stored templates, deliberately not generated by an LLM on each
tick: that would make discovery non-reproducible and spend model budget on
something a human should review periodically (spec section 35).

Two kinds of query live here, and the distinction is the point:

``ROUTINE``
    Conventional recent-news and thematic searches -- keyword-shaped, answered
    well by a classical index, and cheap.  Brave answers these.

``SEMANTIC``
    Second-order questions: not "what happened to transformers this week" but
    "which public companies gain from a transformer shortage".  A keyword index
    answers these badly; an embedding index answers them well, at roughly ten
    times the price.  Exa answers these, a handful of times a day.

Duplicating routine queries into the semantic provider would double the bill to
rediscover the same articles, which is why they are separate lists on separate
schedules rather than one list run through both backends.
"""

from __future__ import annotations

from dataclasses import dataclass, field

import sqlalchemy as sa
from sqlalchemy.ext.asyncio import AsyncSession

from stockbrain.db.models.system import DiscoveryQuery, DiscoveryTopic
from stockbrain.enums import WebDiscoveryKind
from stockbrain.logging import get_logger

__all__ = [
    "DEFAULT_TOPICS",
    "SEMANTIC_TOPIC_SLUG",
    "TopicSeed",
    "seed_default_topics",
    "seed_semantic_topic",
]

log = get_logger(__name__)

#: The seeded semantic topic's slug.  Named as a constant because the migration
#: that adds it to an already-populated database has to find it by slug and must
#: not re-insert it on a second run.
SEMANTIC_TOPIC_SLUG = "second_order_exposure"


@dataclass(frozen=True, slots=True)
class TopicSeed:
    slug: str
    name: str
    description: str
    interval_minutes: int
    freshness_days: int
    kind: WebDiscoveryKind = WebDiscoveryKind.ROUTINE
    result_limit: int = 10
    queries: tuple[str, ...] = field(default_factory=tuple)
    enabled: bool = True


#: Conservative defaults.  The intervals below are what a *seeded* topic asks
#: for; ``Settings.min_query_interval_minutes`` is a floor applied on top of
#: them at enqueue time, so a slower configuration always wins.
#:
#: Phase 2 seeded these at 20-60 minutes with **four** topics enabled and nine
#: enabled queries between them: 21 searches an hour, 504 a day, and -- because
#: search also scraped every result -- around 12,000 credits a day against a
#: 1,000-credit monthly allowance.  Two routine topics are enabled by default at
#: twelve-hour intervals, and thematic drift is a thing you look at twice a day
#: rather than three times an hour.
DEFAULT_TOPICS: tuple[TopicSeed, ...] = (
    TopicSeed(
        slug="ai_infrastructure",
        name="AI infrastructure",
        description="Data centre build-out, accelerators, and the power and cooling behind them.",
        interval_minutes=720,
        freshness_days=7,
        queries=(
            '"AI data center" investment announcement',
            '"data centre" power infrastructure contract',
            "hyperscaler capacity expansion electricity cooling",
        ),
    ),
    TopicSeed(
        slug="semiconductors",
        name="Semiconductors",
        description="Fabs, equipment, export controls and supply agreements.",
        interval_minutes=720,
        freshness_days=7,
        queries=(
            "semiconductor fab capacity expansion announcement",
            "chip export controls restriction announcement",
        ),
    ),
    TopicSeed(
        slug="power_grid",
        name="Power grid and transformers",
        description="Grid capacity, transformers, transmission and interconnection queues.",
        interval_minutes=720,
        freshness_days=7,
        queries=(
            "grid transformer order backlog utility",
            "transmission interconnection capacity investment",
        ),
        enabled=False,
    ),
    TopicSeed(
        slug="defence",
        name="Defence procurement",
        description="Contract awards, procurement programmes and defence budgets.",
        interval_minutes=720,
        freshness_days=7,
        queries=(
            "defence contract awarded ministry",
            "military procurement contract award",
        ),
        enabled=False,
    ),
    TopicSeed(
        slug="nuclear",
        name="Nuclear and SMR",
        description="Reactor projects, small modular reactors, uranium supply.",
        interval_minutes=1440,
        freshness_days=14,
        queries=(
            "nuclear reactor project contract approval",
            "small modular reactor investment agreement",
        ),
        enabled=False,
    ),
    TopicSeed(
        slug="regulation",
        name="Major regulation and sanctions",
        description="Sanctions, export controls and significant regulatory decisions.",
        interval_minutes=720,
        freshness_days=7,
        queries=(
            "sanctions export controls announced company",
            "regulator decision fine major company",
        ),
        enabled=False,
    ),
    TopicSeed(
        slug="biotech_regulatory",
        name="FDA and biotech regulatory",
        description="Approvals, rejections, clinical holds and advisory committee outcomes.",
        interval_minutes=1440,
        freshness_days=7,
        queries=(
            "FDA approval rejection complete response letter",
            "phase 3 trial results primary endpoint",
        ),
        enabled=False,
    ),
    TopicSeed(
        slug="supply_chain",
        name="Supply-chain disruption",
        description="Shutdowns, shortages, logistics failures and force majeure.",
        interval_minutes=1440,
        freshness_days=7,
        queries=(
            "plant shutdown production halt supply disruption",
            "force majeure shortage component supply",
        ),
        enabled=False,
    ),
    #: The semantic topic.  One topic, one query a day by default, and it asks a
    #: *question* rather than listing keywords -- that phrasing is what an
    #: embedding index is for, and it is exactly what a keyword index handles
    #: worst.
    TopicSeed(
        slug=SEMANTIC_TOPIC_SLUG,
        name="Second-order exposure",
        description=(
            "Indirect beneficiaries: who gains when a constraint appears somewhere "
            "else in the chain."
        ),
        kind=WebDiscoveryKind.SEMANTIC,
        # A day between runs, and the configured semantic floor is a day as
        # well. The answer to "who benefits from a shortage" moves over weeks.
        interval_minutes=1440,
        freshness_days=30,
        result_limit=10,
        queries=(
            "public companies benefiting from transformer shortages caused by datacenter expansion",
            "suppliers gaining from electricity grid interconnection bottlenecks",
            "listed companies that are indirect beneficiaries of semiconductor export restrictions",
            "public companies newly exposed to an emerging industrial capacity constraint",
        ),
        enabled=False,
    ),
)


async def seed_default_topics(session: AsyncSession) -> int:
    """Insert the default topics when none exist.  Returns the number inserted.

    Idempotent and non-destructive: if the user has any topics at all, this does
    nothing. Restoring the defaults after deleting them is a deliberate user
    action, not a side effect of restarting the container.
    """
    existing = (
        await session.execute(sa.select(sa.func.count()).select_from(DiscoveryTopic))
    ).scalar_one()
    if existing:
        return 0

    for seed in DEFAULT_TOPICS:
        _insert_topic(session, seed)
        await session.flush()

    await session.flush()
    log.info("discovery_topics_seeded", count=len(DEFAULT_TOPICS))
    return len(DEFAULT_TOPICS)


async def seed_semantic_topic(session: AsyncSession) -> bool:
    """Add the semantic topic to a database that already has routine ones.

    A deployment upgraded from Phase 9 has eight routine topics and would never
    reach :func:`seed_default_topics` again, so the one genuinely new thing the
    provider split introduces would never appear.  Matched by slug and inserted
    at most once; a user who deletes it keeps it deleted.
    """
    seed = next(s for s in DEFAULT_TOPICS if s.slug == SEMANTIC_TOPIC_SLUG)
    existing = (
        await session.execute(sa.select(DiscoveryTopic.id).where(DiscoveryTopic.slug == seed.slug))
    ).scalar_one_or_none()
    if existing is not None:
        return False
    _insert_topic(session, seed)
    await session.flush()
    log.info("semantic_topic_seeded", slug=seed.slug)
    return True


def _insert_topic(session: AsyncSession, seed: TopicSeed) -> None:
    topic = DiscoveryTopic(
        slug=seed.slug,
        name=seed.name,
        description=seed.description,
        enabled=seed.enabled,
        interval_minutes=seed.interval_minutes,
        result_limit=seed.result_limit,
        freshness_days=seed.freshness_days,
        include_domains=[],
        exclude_domains=[],
    )
    session.add(topic)
    # Attached through the relationship rather than by id, so SQLAlchemy orders
    # the inserts itself and the caller needs only one flush.
    for query in seed.queries:
        session.add(
            DiscoveryQuery(
                topic=topic,
                query=query,
                enabled=True,
                search_kind=seed.kind,
            )
        )
