"""Discovery topic registry.

Topics are stored in PostgreSQL and edited by the user, not hard-coded into
logic. The list below is only the *initial seed*, applied once when the table is
empty; after that the database is authoritative and a redeploy never resurrects
a topic the user disabled or deleted.

Query strings are stored templates, deliberately not generated by an LLM on each
tick: that would make discovery non-reproducible and spend model budget on
something a human should review periodically (spec section 35).
"""

from __future__ import annotations

from dataclasses import dataclass, field

import sqlalchemy as sa
from sqlalchemy.ext.asyncio import AsyncSession

from stockbrain.db.models.system import DiscoveryQuery, DiscoveryTopic
from stockbrain.logging import get_logger

__all__ = ["DEFAULT_TOPICS", "TopicSeed", "seed_default_topics"]

log = get_logger(__name__)


@dataclass(frozen=True, slots=True)
class TopicSeed:
    slug: str
    name: str
    description: str
    interval_minutes: int
    freshness: str
    queries: tuple[str, ...] = field(default_factory=tuple)
    enabled: bool = True


#: Conservative defaults: only a handful enabled, so a fresh install does not
#: immediately burn Firecrawl credits on sixteen themes.
DEFAULT_TOPICS: tuple[TopicSeed, ...] = (
    TopicSeed(
        slug="ai_infrastructure",
        name="AI infrastructure",
        description="Data centre build-out, accelerators, and the power and cooling behind them.",
        interval_minutes=20,
        freshness="qdr:h",
        queries=(
            '"AI data center" investment announcement',
            '"data centre" power infrastructure contract',
            "hyperscaler capacity expansion electricity cooling",
        ),
    ),
    TopicSeed(
        slug="semiconductors",
        name="Semiconductors",
        description="Fabs, equipment, export controls and supply agreements.",
        interval_minutes=30,
        freshness="qdr:d",
        queries=(
            "semiconductor fab capacity expansion announcement",
            "chip export controls restriction announcement",
        ),
    ),
    TopicSeed(
        slug="power_grid",
        name="Power grid and transformers",
        description="Grid capacity, transformers, transmission and interconnection queues.",
        interval_minutes=30,
        freshness="qdr:d",
        queries=(
            "grid transformer order backlog utility",
            "transmission interconnection capacity investment",
        ),
    ),
    TopicSeed(
        slug="defence",
        name="Defence procurement",
        description="Contract awards, procurement programmes and defence budgets.",
        interval_minutes=30,
        freshness="qdr:d",
        queries=(
            "defence contract awarded ministry",
            "military procurement contract award",
        ),
    ),
    TopicSeed(
        slug="nuclear",
        name="Nuclear and SMR",
        description="Reactor projects, small modular reactors, uranium supply.",
        interval_minutes=60,
        freshness="qdr:d",
        queries=(
            "nuclear reactor project contract approval",
            "small modular reactor investment agreement",
        ),
        enabled=False,
    ),
    TopicSeed(
        slug="regulation",
        name="Major regulation and sanctions",
        description="Sanctions, export controls and significant regulatory decisions.",
        interval_minutes=30,
        freshness="qdr:d",
        queries=(
            "sanctions export controls announced company",
            "regulator decision fine major company",
        ),
        enabled=False,
    ),
    TopicSeed(
        slug="biotech_regulatory",
        name="FDA and biotech regulatory",
        description="Approvals, rejections, clinical holds and advisory committee outcomes.",
        interval_minutes=60,
        freshness="qdr:d",
        queries=(
            "FDA approval rejection complete response letter",
            "phase 3 trial results primary endpoint",
        ),
        enabled=False,
    ),
    TopicSeed(
        slug="supply_chain",
        name="Supply-chain disruption",
        description="Shutdowns, shortages, logistics failures and force majeure.",
        interval_minutes=45,
        freshness="qdr:d",
        queries=(
            "plant shutdown production halt supply disruption",
            "force majeure shortage component supply",
        ),
        enabled=False,
    ),
)


async def seed_default_topics(session: AsyncSession) -> int:
    """Insert the default topics when none exist.  Returns the number inserted.

    Idempotent and non-destructive: if the user has any topics at all, this does
    nothing. Restoring the defaults after deleting them is a deliberate user
    action, not a side effect of restarting the container.
    """
    existing = (
        await session.execute(sa.select(sa.func.count()).select_from(DiscoveryTopic))
    ).scalar_one()
    if existing:
        return 0

    for seed in DEFAULT_TOPICS:
        topic = DiscoveryTopic(
            slug=seed.slug,
            name=seed.name,
            description=seed.description,
            enabled=seed.enabled,
            interval_minutes=seed.interval_minutes,
            result_limit=10,
            freshness=seed.freshness,
            include_domains=[],
            exclude_domains=[],
        )
        session.add(topic)
        await session.flush()
        for query in seed.queries:
            session.add(DiscoveryQuery(topic_id=topic.id, query=query, enabled=True))

    await session.flush()
    log.info("discovery_topics_seeded", count=len(DEFAULT_TOPICS))
    return len(DEFAULT_TOPICS)
