"""initial core schema

Revision ID: 1e4f3a52f540
Revises:
Create Date: 2026-09-04 17:27:35.686238+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "1e4f3a52f540"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Native PostgreSQL enum types created implicitly by the ``sa.Enum`` columns
# below.  Alembic's autogenerate does not emit DROP TYPE statements, so the
# downgrade must remove them explicitly or a subsequent upgrade fails with
# "type already exists".
ENUM_TYPES: tuple[str, ...] = (
    "actor_type",
    "approval_channel",
    "approval_stage",
    "broker",
    "event_source_relationship",
    "event_status",
    "execution_outcome",
    "impact_direction",
    "job_status",
    "notification_class",
    "notification_status",
    "order_side",
    "order_type",
    "price_source",
    "proposal_status",
    "provider_status",
    "research_status",
    "source_provider",
    "thesis_action",
    "time_horizon",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_settings",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("updated_by", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_app_settings")),
    )
    op.create_table(
        "audit_log",
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "actor_type",
            sa.Enum("SYSTEM", "USER", "LLM", "BROKER", name="actor_type"),
            nullable=False,
        ),
        sa.Column("actor_id", sa.Text(), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("entity_type", sa.Text(), nullable=True),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index("ix_audit_log_action", "audit_log", ["action"], unique=False)
    op.create_index("ix_audit_log_entity", "audit_log", ["entity_type", "entity_id"], unique=False)
    op.create_index("ix_audit_log_occurred_at", "audit_log", ["occurred_at"], unique=False)
    op.create_table(
        "companies",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("primary_symbol", sa.Text(), nullable=True),
        sa.Column("exchange", sa.Text(), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("isin", sa.String(length=12), nullable=True),
        sa.Column("cik", sa.String(length=10), nullable=True),
        sa.Column("sector", sa.Text(), nullable=True),
        sa.Column("industry", sa.Text(), nullable=True),
        sa.Column(
            "aliases",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("is_watchlisted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_companies")),
    )
    op.create_index("ix_companies_name", "companies", ["name"], unique=False)
    op.create_index("ix_companies_primary_symbol", "companies", ["primary_symbol"], unique=False)
    op.create_index(
        "uq_companies_cik",
        "companies",
        ["cik"],
        unique=True,
        postgresql_where=sa.text("cik IS NOT NULL"),
    )
    op.create_index(
        "uq_companies_isin",
        "companies",
        ["isin"],
        unique=True,
        postgresql_where=sa.text("isin IS NOT NULL"),
    )
    op.create_table(
        "discovery_topics",
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("interval_minutes", sa.Integer(), server_default="30", nullable=False),
        sa.Column("result_limit", sa.Integer(), server_default="10", nullable=False),
        sa.Column("freshness", sa.Text(), server_default="qdr:d", nullable=False),
        sa.Column(
            "include_domains",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "exclude_domains",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_discovery_topics")),
        sa.UniqueConstraint("slug", name="uq_discovery_topics_slug"),
    )
    op.create_table(
        "events",
        sa.Column("event_type", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("importance_score", sa.Float(), nullable=True),
        sa.Column("novelty_score", sa.Float(), nullable=True),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column("candidate_score", sa.Float(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "CLASSIFYING",
                "CLASSIFIED",
                "CLASSIFICATION_FAILED",
                "IRRELEVANT",
                "CANDIDATE",
                "RESEARCHING",
                "RESEARCHED",
                "ARCHIVED",
                name="event_status",
            ),
            server_default="NEW",
            nullable=False,
        ),
        sa.Column("classifier_model", sa.Text(), nullable=True),
        sa.Column("classifier_prompt_version", sa.Text(), nullable=True),
        sa.Column("classifier_output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "topics",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "importance_score IS NULL OR (importance_score >= 0 AND importance_score <= 1)",
            name=op.f("ck_events_importance_range"),
        ),
        sa.CheckConstraint(
            "novelty_score IS NULL OR (novelty_score >= 0 AND novelty_score <= 1)",
            name=op.f("ck_events_novelty_range"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
    )
    op.create_index("ix_events_importance", "events", ["importance_score"], unique=False)
    op.create_index(
        "ix_events_status_first_seen", "events", ["status", "first_seen_at"], unique=False
    )
    op.create_table(
        "jobs",
        sa.Column("job_type", sa.Text(), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("PENDING", "RUNNING", "SUCCEEDED", "FAILED", "CANCELLED", name="job_status"),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), server_default="100", nullable=False),
        sa.Column(
            "run_after", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default="3", nullable=False),
        sa.Column("locked_by", sa.Text(), nullable=True),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("dedupe_key", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    op.create_index(
        "ix_jobs_claim",
        "jobs",
        ["priority", "created_at"],
        unique=False,
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.create_index("ix_jobs_status_run_after", "jobs", ["status", "run_after"], unique=False)
    op.create_index(
        "uq_jobs_dedupe_key_active",
        "jobs",
        ["dedupe_key"],
        unique=True,
        postgresql_where=sa.text("dedupe_key IS NOT NULL AND status IN ('PENDING', 'RUNNING')"),
    )
    op.create_table(
        "notifications",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "notification_class",
            sa.Enum(
                "CRITICAL",
                "PROPOSAL",
                "PORTFOLIO_EVENT",
                "SYSTEM_WARNING",
                "DAILY_SUMMARY",
                name="notification_class",
            ),
            nullable=False,
        ),
        sa.Column("channel", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "SENT", "FAILED", "SUPPRESSED", name="notification_status"),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("entity_type", sa.Text(), nullable=True),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivery_reference", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("dedupe_key", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index("ix_notifications_created_at", "notifications", ["created_at"], unique=False)
    op.create_index("ix_notifications_status", "notifications", ["status"], unique=False)
    op.create_index(
        "uq_notifications_dedupe_key",
        "notifications",
        ["dedupe_key"],
        unique=True,
        postgresql_where=sa.text("dedupe_key IS NOT NULL"),
    )
    op.create_table(
        "portfolio_snapshots",
        sa.Column("broker", sa.Enum("TRADING212", name="broker"), nullable=False),
        sa.Column("account_id", sa.Text(), nullable=True),
        sa.Column(
            "captured_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("cash_available", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("invested_value", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("result_value", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("total_value", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column(
            "raw",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolio_snapshots")),
    )
    op.create_index(
        "ix_portfolio_snapshots_broker_captured",
        "portfolio_snapshots",
        ["broker", "captured_at"],
        unique=False,
    )
    op.create_table(
        "provider_health",
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("HEALTHY", "DEGRADED", "DOWN", "DISABLED", "UNKNOWN", name="provider_status"),
            server_default="UNKNOWN",
            nullable=False,
        ),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("last_ok_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "metrics",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("provider", name=op.f("pk_provider_health")),
    )
    op.create_table(
        "sources",
        sa.Column(
            "provider",
            sa.Enum("ALPACA", "FIRECRAWL", "SEC", "MANUAL", name="source_provider"),
            nullable=False,
        ),
        sa.Column("provider_item_id", sa.Text(), nullable=True),
        sa.Column("canonical_url", sa.Text(), nullable=True),
        sa.Column("original_url", sa.Text(), nullable=True),
        sa.Column("source_name", sa.Text(), nullable=True),
        sa.Column("source_category", sa.Text(), nullable=True),
        sa.Column("headline", sa.Text(), nullable=True),
        sa.Column("author", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at_source", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("raw_content", sa.Text(), nullable=True),
        sa.Column("normalized_text", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sources")),
    )
    op.create_index("ix_sources_content_hash", "sources", ["content_hash"], unique=False)
    op.create_index("ix_sources_published_at", "sources", ["published_at"], unique=False)
    op.create_index("ix_sources_received_at", "sources", ["received_at"], unique=False)
    op.create_index(
        "uq_sources_canonical_url_hash",
        "sources",
        ["canonical_url", "content_hash"],
        unique=True,
        postgresql_where=sa.text("canonical_url IS NOT NULL"),
    )
    op.create_index(
        "uq_sources_provider_item",
        "sources",
        ["provider", "provider_item_id"],
        unique=True,
        postgresql_where=sa.text("provider_item_id IS NOT NULL"),
    )
    op.create_table(
        "users",
        sa.Column("username", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("is_owner", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("username", name="uq_users_username"),
    )
    op.create_index(
        "uq_users_telegram_user_id",
        "users",
        ["telegram_user_id"],
        unique=True,
        postgresql_where=sa.text("telegram_user_id IS NOT NULL"),
    )
    op.create_table(
        "broker_instruments",
        sa.Column("company_id", sa.Uuid(), nullable=True),
        sa.Column("broker", sa.Enum("TRADING212", name="broker"), nullable=False),
        sa.Column("broker_ticker", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("short_name", sa.Text(), nullable=True),
        sa.Column("isin", sa.String(length=12), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("instrument_type", sa.Text(), nullable=True),
        sa.Column("extended_hours", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("min_trade_quantity", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("max_open_quantity", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("working_schedule_id", sa.BigInteger(), nullable=True),
        sa.Column("added_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "raw_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_broker_instruments_company_id_companies"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_broker_instruments")),
        sa.UniqueConstraint(
            "broker", "broker_ticker", name="uq_broker_instruments_broker_broker_ticker"
        ),
    )
    op.create_index(
        "ix_broker_instruments_company_id", "broker_instruments", ["company_id"], unique=False
    )
    op.create_index("ix_broker_instruments_isin", "broker_instruments", ["isin"], unique=False)
    op.create_table(
        "company_aliases",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("alias", sa.Text(), nullable=False),
        sa.Column("alias_normalized", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), server_default="MANUAL", nullable=False),
        sa.Column("confidence", sa.Float(), server_default="1.0", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_company_aliases_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_company_aliases")),
        sa.UniqueConstraint(
            "alias_normalized", "company_id", name="uq_company_aliases_alias_company"
        ),
    )
    op.create_index(
        "ix_company_aliases_alias_normalized", "company_aliases", ["alias_normalized"], unique=False
    )
    op.create_table(
        "discovery_queries",
        sa.Column("topic_id", sa.Uuid(), nullable=False),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), server_default="0", nullable=False),
        sa.Column("results_seen", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("credits_used", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["discovery_topics.id"],
            name=op.f("fk_discovery_queries_topic_id_discovery_topics"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_discovery_queries")),
        sa.UniqueConstraint("topic_id", "query", name="uq_discovery_queries_topic_id_query"),
    )
    op.create_table(
        "event_company_impacts",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=True),
        sa.Column("company_name_hint", sa.Text(), nullable=False),
        sa.Column("ticker_hint", sa.Text(), nullable=True),
        sa.Column("exchange_hint", sa.Text(), nullable=True),
        sa.Column(
            "direction",
            sa.Enum("POSITIVE", "NEGATIVE", "MIXED", "UNKNOWN", name="impact_direction"),
            nullable=False,
        ),
        sa.Column("relationship_type", sa.Text(), nullable=True),
        sa.Column("materiality_score", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("resolution_confidence", sa.Float(), nullable=True),
        sa.Column("resolution_method", sa.Text(), nullable=True),
        sa.Column("resolution_notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_event_company_impacts_confidence_range"),
        ),
        sa.CheckConstraint(
            "materiality_score >= 0 AND materiality_score <= 1",
            name=op.f("ck_event_company_impacts_materiality_range"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_event_company_impacts_company_id_companies"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_event_company_impacts_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_company_impacts")),
    )
    op.create_index(
        "ix_event_company_impacts_company_id", "event_company_impacts", ["company_id"], unique=False
    )
    op.create_index(
        "ix_event_company_impacts_event_id", "event_company_impacts", ["event_id"], unique=False
    )
    op.create_table(
        "event_sources",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column(
            "relationship_type",
            sa.Enum(
                "PRIMARY",
                "CORROBORATING",
                "UPDATE",
                "CONTRADICTING",
                name="event_source_relationship",
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_event_sources_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_event_sources_source_id_sources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("event_id", "source_id", name=op.f("pk_event_sources")),
    )
    op.create_table(
        "positions",
        sa.Column("broker", sa.Enum("TRADING212", name="broker"), nullable=False),
        sa.Column("account_id", sa.Text(), server_default="default", nullable=False),
        sa.Column("broker_ticker", sa.Text(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("quantity_available", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("average_price", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("current_price", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("ppl", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("initial_fill_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "last_synced_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "raw",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_positions_company_id_companies"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_positions")),
        sa.UniqueConstraint(
            "broker",
            "account_id",
            "broker_ticker",
            name="uq_positions_broker_account_id_broker_ticker",
        ),
    )
    op.create_table(
        "research_runs",
        sa.Column("event_id", sa.Uuid(), nullable=True),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "SUCCEEDED",
                "FAILED",
                "TIMED_OUT",
                "CANCELLED",
                name="research_status",
            ),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("trigger", sa.Text(), server_default="EVENT", nullable=False),
        sa.Column(
            "as_of", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tradingagents_version", sa.Text(), nullable=True),
        sa.Column("quick_model", sa.Text(), nullable=True),
        sa.Column("deep_model", sa.Text(), nullable=True),
        sa.Column("prompt_version", sa.Text(), nullable=True),
        sa.Column("research_packet", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("raw_reports", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("structured_decision", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("token_usage", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("estimated_cost_usd", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_research_runs_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_research_runs_event_id_events"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_runs")),
    )
    op.create_index(
        "ix_research_runs_event_company", "research_runs", ["event_id", "company_id"], unique=False
    )
    op.create_index("ix_research_runs_status", "research_runs", ["status"], unique=False)
    op.create_table(
        "llm_calls",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("provider", sa.Text(), server_default="deepseek", nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("prompt_version", sa.Text(), nullable=True),
        sa.Column(
            "thinking_enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("research_run_id", sa.Uuid(), nullable=True),
        sa.Column("event_id", sa.Uuid(), nullable=True),
        sa.Column("attempt", sa.Integer(), server_default="1", nullable=False),
        sa.Column("succeeded", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("used", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cached_input_tokens", sa.Integer(), nullable=True),
        sa.Column("estimated_cost_usd", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("response_excerpt", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_llm_calls_event_id_events"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["research_run_id"],
            ["research_runs.id"],
            name=op.f("fk_llm_calls_research_run_id_research_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_calls")),
    )
    op.create_index("ix_llm_calls_created_at", "llm_calls", ["created_at"], unique=False)
    op.create_index("ix_llm_calls_purpose_model", "llm_calls", ["purpose", "model"], unique=False)
    op.create_table(
        "theses",
        sa.Column("research_run_id", sa.Uuid(), nullable=False),
        sa.Column(
            "action",
            sa.Enum("BUY", "HOLD", "REDUCE", "SELL", "NO_ACTION", name="thesis_action"),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "time_horizon",
            sa.Enum("intraday", "days", "weeks", "months", name="time_horizon"),
            nullable=False,
        ),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("bull_case", sa.Text(), nullable=True),
        sa.Column("bear_case", sa.Text(), nullable=True),
        sa.Column(
            "catalysts",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "risks",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "invalidation_conditions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "evidence_source_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("target_logic", sa.Text(), nullable=True),
        sa.Column("original_thesis_id", sa.Uuid(), nullable=True),
        sa.Column("supersedes_thesis_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name=op.f("ck_theses_confidence_range")
        ),
        sa.ForeignKeyConstraint(
            ["original_thesis_id"],
            ["theses.id"],
            name=op.f("fk_theses_original_thesis_id_theses"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["research_run_id"],
            ["research_runs.id"],
            name=op.f("fk_theses_research_run_id_research_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_thesis_id"],
            ["theses.id"],
            name=op.f("fk_theses_supersedes_thesis_id_theses"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_theses")),
    )
    op.create_index("ix_theses_research_run_id", "theses", ["research_run_id"], unique=False)
    op.create_table(
        "trade_proposals",
        sa.Column("thesis_id", sa.Uuid(), nullable=True),
        sa.Column("event_id", sa.Uuid(), nullable=True),
        sa.Column("company_id", sa.Uuid(), nullable=True),
        sa.Column("broker_instrument_id", sa.Uuid(), nullable=True),
        sa.Column("broker", sa.Enum("TRADING212", name="broker"), nullable=False),
        sa.Column("broker_ticker", sa.Text(), nullable=False),
        sa.Column("account_id", sa.Text(), server_default="default", nullable=False),
        sa.Column("broker_environment", sa.Text(), server_default="demo", nullable=False),
        sa.Column("side", sa.Enum("BUY", "SELL", name="order_side"), nullable=False),
        sa.Column(
            "order_type",
            sa.Enum("MARKET", "LIMIT", "STOP", "STOP_LIMIT", name="order_type"),
            nullable=False,
        ),
        sa.Column("proposed_quantity", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("limit_price", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("reference_price", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("reference_currency", sa.String(length=3), nullable=False),
        sa.Column(
            "price_source",
            sa.Enum(
                "ALPACA_IEX",
                "ALPACA_SIP",
                "ALPACA_DELAYED_SIP",
                "YFINANCE",
                "BROKER_T212",
                "MANUAL",
                name="price_source",
            ),
            nullable=False,
        ),
        sa.Column("quote_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("quote_age_ms", sa.Integer(), nullable=False),
        sa.Column("estimated_notional", sa.Numeric(precision=24, scale=4), nullable=False),
        sa.Column("account_currency", sa.String(length=3), nullable=False),
        sa.Column(
            "risk_snapshot",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("risk_snapshot_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "READY",
                "NOTIFIED",
                "APPROVAL_PENDING",
                "APPROVED",
                "REJECTED",
                "EXPIRED",
                "EXECUTING",
                "EXECUTED",
                "EXECUTION_AMBIGUOUS",
                "FAILED",
                "CANCELLED",
                name="proposal_status",
            ),
            server_default="DRAFT",
            nullable=False,
        ),
        sa.Column("status_reason", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by", sa.Text(), nullable=True),
        sa.Column(
            "approved_channel", sa.Enum("WEB", "TELEGRAM", name="approval_channel"), nullable=True
        ),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejected_by", sa.Text(), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "proposed_quantity > 0", name=op.f("ck_trade_proposals_quantity_positive")
        ),
        sa.CheckConstraint(
            "quote_age_ms >= 0", name=op.f("ck_trade_proposals_quote_age_non_negative")
        ),
        sa.CheckConstraint(
            "reference_price > 0", name=op.f("ck_trade_proposals_reference_price_positive")
        ),
        sa.ForeignKeyConstraint(
            ["broker_instrument_id"],
            ["broker_instruments.id"],
            name=op.f("fk_trade_proposals_broker_instrument_id_broker_instruments"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_trade_proposals_company_id_companies"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_trade_proposals_event_id_events"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["thesis_id"],
            ["theses.id"],
            name=op.f("fk_trade_proposals_thesis_id_theses"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trade_proposals")),
    )
    op.create_index(
        "ix_trade_proposals_created_at", "trade_proposals", ["created_at"], unique=False
    )
    op.create_index(
        "ix_trade_proposals_status_expires",
        "trade_proposals",
        ["status", "expires_at"],
        unique=False,
    )
    op.create_index(
        "uq_trade_proposals_active_instrument",
        "trade_proposals",
        ["broker", "account_id", "broker_ticker"],
        unique=True,
        postgresql_where=sa.text(
            "status IN ('DRAFT', 'READY', 'NOTIFIED', 'APPROVAL_PENDING', 'APPROVED', 'EXECUTING', 'EXECUTION_AMBIGUOUS')"
        ),
    )
    op.create_table(
        "approval_actions",
        sa.Column("proposal_id", sa.Uuid(), nullable=False),
        sa.Column("channel", sa.Enum("WEB", "TELEGRAM", name="approval_channel"), nullable=False),
        sa.Column("stage", sa.Enum("APPROVE", "CONFIRM", name="approval_stage"), nullable=False),
        sa.Column("opaque_token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_identifier", sa.Text(), nullable=False),
        sa.Column("parent_action_id", sa.Uuid(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "context",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_action_id"],
            ["approval_actions.id"],
            name=op.f("fk_approval_actions_parent_action_id_approval_actions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["trade_proposals.id"],
            name=op.f("fk_approval_actions_proposal_id_trade_proposals"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approval_actions")),
        sa.UniqueConstraint("opaque_token_hash", name="uq_approval_actions_opaque_token_hash"),
    )
    op.create_index(
        "ix_approval_actions_proposal_id", "approval_actions", ["proposal_id"], unique=False
    )
    op.create_table(
        "execution_attempts",
        sa.Column("proposal_id", sa.Uuid(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("broker_environment", sa.Text(), nullable=False),
        sa.Column(
            "request_payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("sent_to_broker", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("response_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("broker_order_id", sa.Text(), nullable=True),
        sa.Column(
            "outcome",
            sa.Enum(
                "PENDING",
                "FAILED_BEFORE_SEND",
                "SUBMITTED",
                "REJECTED_BY_BROKER",
                "AMBIGUOUS",
                "RECONCILED_FILLED",
                "RECONCILED_NOT_PLACED",
                name="execution_outcome",
            ),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("ambiguous", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("actor_identifier", sa.Text(), nullable=True),
        sa.Column("rate_limit_headers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "NOT sent_to_broker OR sent_at IS NOT NULL",
            name=op.f("ck_execution_attempts_sent_requires_timestamp"),
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["trade_proposals.id"],
            name=op.f("fk_execution_attempts_proposal_id_trade_proposals"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_execution_attempts")),
        sa.UniqueConstraint(
            "proposal_id", "attempt_number", name="uq_execution_attempts_proposal_id_attempt_number"
        ),
    )
    op.create_index(
        "ix_execution_attempts_outcome", "execution_attempts", ["outcome"], unique=False
    )
    op.create_index(
        "uq_execution_attempts_sent_once",
        "execution_attempts",
        ["proposal_id"],
        unique=True,
        postgresql_where=sa.text("sent_to_broker"),
    )
    op.create_table(
        "broker_orders",
        sa.Column("broker", sa.Enum("TRADING212", name="broker"), nullable=False),
        sa.Column("broker_order_id", sa.Text(), nullable=False),
        sa.Column("proposal_id", sa.Uuid(), nullable=True),
        sa.Column("execution_attempt_id", sa.Uuid(), nullable=True),
        sa.Column("broker_ticker", sa.Text(), nullable=False),
        sa.Column("side", sa.Enum("BUY", "SELL", name="order_side"), nullable=False),
        sa.Column(
            "order_type",
            sa.Enum("MARKET", "LIMIT", "STOP", "STOP_LIMIT", name="order_type"),
            nullable=False,
        ),
        sa.Column("quantity", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("filled_quantity", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("limit_price", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("stop_price", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("filled_value", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("broker_status", sa.Text(), nullable=True),
        sa.Column("is_terminal", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "discovered_by_reconciliation",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "last_synced_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "raw",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["execution_attempt_id"],
            ["execution_attempts.id"],
            name=op.f("fk_broker_orders_execution_attempt_id_execution_attempts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["trade_proposals.id"],
            name=op.f("fk_broker_orders_proposal_id_trade_proposals"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_broker_orders")),
        sa.UniqueConstraint(
            "broker", "broker_order_id", name="uq_broker_orders_broker_broker_order_id"
        ),
    )
    op.create_index("ix_broker_orders_proposal_id", "broker_orders", ["proposal_id"], unique=False)
    op.create_index("ix_broker_orders_ticker", "broker_orders", ["broker_ticker"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_broker_orders_ticker", table_name="broker_orders")
    op.drop_index("ix_broker_orders_proposal_id", table_name="broker_orders")
    op.drop_table("broker_orders")
    op.drop_index(
        "uq_execution_attempts_sent_once",
        table_name="execution_attempts",
        postgresql_where=sa.text("sent_to_broker"),
    )
    op.drop_index("ix_execution_attempts_outcome", table_name="execution_attempts")
    op.drop_table("execution_attempts")
    op.drop_index("ix_approval_actions_proposal_id", table_name="approval_actions")
    op.drop_table("approval_actions")
    op.drop_index(
        "uq_trade_proposals_active_instrument",
        table_name="trade_proposals",
        postgresql_where=sa.text(
            "status IN ('DRAFT', 'READY', 'NOTIFIED', 'APPROVAL_PENDING', 'APPROVED', 'EXECUTING', 'EXECUTION_AMBIGUOUS')"
        ),
    )
    op.drop_index("ix_trade_proposals_status_expires", table_name="trade_proposals")
    op.drop_index("ix_trade_proposals_created_at", table_name="trade_proposals")
    op.drop_table("trade_proposals")
    op.drop_index("ix_theses_research_run_id", table_name="theses")
    op.drop_table("theses")
    op.drop_index("ix_llm_calls_purpose_model", table_name="llm_calls")
    op.drop_index("ix_llm_calls_created_at", table_name="llm_calls")
    op.drop_table("llm_calls")
    op.drop_index("ix_research_runs_status", table_name="research_runs")
    op.drop_index("ix_research_runs_event_company", table_name="research_runs")
    op.drop_table("research_runs")
    op.drop_table("positions")
    op.drop_table("event_sources")
    op.drop_index("ix_event_company_impacts_event_id", table_name="event_company_impacts")
    op.drop_index("ix_event_company_impacts_company_id", table_name="event_company_impacts")
    op.drop_table("event_company_impacts")
    op.drop_table("discovery_queries")
    op.drop_index("ix_company_aliases_alias_normalized", table_name="company_aliases")
    op.drop_table("company_aliases")
    op.drop_index("ix_broker_instruments_isin", table_name="broker_instruments")
    op.drop_index("ix_broker_instruments_company_id", table_name="broker_instruments")
    op.drop_table("broker_instruments")
    op.drop_index(
        "uq_users_telegram_user_id",
        table_name="users",
        postgresql_where=sa.text("telegram_user_id IS NOT NULL"),
    )
    op.drop_table("users")
    op.drop_index(
        "uq_sources_provider_item",
        table_name="sources",
        postgresql_where=sa.text("provider_item_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_sources_canonical_url_hash",
        table_name="sources",
        postgresql_where=sa.text("canonical_url IS NOT NULL"),
    )
    op.drop_index("ix_sources_received_at", table_name="sources")
    op.drop_index("ix_sources_published_at", table_name="sources")
    op.drop_index("ix_sources_content_hash", table_name="sources")
    op.drop_table("sources")
    op.drop_table("provider_health")
    op.drop_index("ix_portfolio_snapshots_broker_captured", table_name="portfolio_snapshots")
    op.drop_table("portfolio_snapshots")
    op.drop_index(
        "uq_notifications_dedupe_key",
        table_name="notifications",
        postgresql_where=sa.text("dedupe_key IS NOT NULL"),
    )
    op.drop_index("ix_notifications_status", table_name="notifications")
    op.drop_index("ix_notifications_created_at", table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(
        "uq_jobs_dedupe_key_active",
        table_name="jobs",
        postgresql_where=sa.text("dedupe_key IS NOT NULL AND status IN ('PENDING', 'RUNNING')"),
    )
    op.drop_index("ix_jobs_status_run_after", table_name="jobs")
    op.drop_index(
        "ix_jobs_claim", table_name="jobs", postgresql_where=sa.text("status = 'PENDING'")
    )
    op.drop_table("jobs")
    op.drop_index("ix_events_status_first_seen", table_name="events")
    op.drop_index("ix_events_importance", table_name="events")
    op.drop_table("events")
    op.drop_table("discovery_topics")
    op.drop_index(
        "uq_companies_isin", table_name="companies", postgresql_where=sa.text("isin IS NOT NULL")
    )
    op.drop_index(
        "uq_companies_cik", table_name="companies", postgresql_where=sa.text("cik IS NOT NULL")
    )
    op.drop_index("ix_companies_primary_symbol", table_name="companies")
    op.drop_index("ix_companies_name", table_name="companies")
    op.drop_table("companies")
    op.drop_index("ix_audit_log_occurred_at", table_name="audit_log")
    op.drop_index("ix_audit_log_entity", table_name="audit_log")
    op.drop_index("ix_audit_log_action", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_table("app_settings")
    # ### end Alembic commands ###
    for enum_name in ENUM_TYPES:
        op.execute(sa.text(f"DROP TYPE IF EXISTS {enum_name}"))
